---
title: "Kbay_physical"
author: "rpdunn"
date: "March 14, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(skimr)
library(lubridate)

data<-read_csv("https://raw.githubusercontent.com/robertpdunn/kbay_physical/master/data_raw/coral_health_allreefs.csv",  na=c("","NA")) #load data
str(data)

```

Tidy some data

```{r tidying data}
data_tidy<-data %>% janitor::clean_names()  #clean column names
names(data_tidy) #check it out
data_tidy<- data_tidy %>% 
  gather(key= obs_type_date,value=obs_values, dplyr::starts_with('x'))  #gather into long format, but keep 'reef', 'species' and
                                                                              #'colony' outside the gather

head(data_tidy, 10)
colnames(data_tidy)<-c("reef", "species", "colony", "date", "health_score") #fix column names
head(data_tidy,10)

data_tidy$date<-gsub("x", "", data_tidy$date)  #remove x's 
head(data_tidy, 10)
data_tidy$reef<-gsub("HIMB","himb",data_tidy$reef) #change HIMB to himb

data_tidy<- data_tidy %>%
  mutate(health_score=str_replace(health_score,"missing-rolled down the hill","NA"))  #remove random string

data_tidy$reef<- sub("^","reef_", data_tidy$reef)  #add reef_ in front of all reef names
head(data_tidy)
unique(data_tidy$reef) #check that it worked

data_tidy<- data_tidy %>%
  mutate("year_month"=floor_date(as.Date(data_tidy$date,'%m_%d_%Y'),unit="month")) #fix month formats
head(data_tidy)
data_tidy$health_score<-as.integer(data_tidy$health_score)  #change health scores to integers
str(data_tidy)
head(data_tidy)
 
#now take the average monthly health score across colonies 
coral_health_monthly <- data_tidy %>% 
  group_by(reef, species, year_month) %>%
  summarise(health_score_mean=mean(health_score,na.rm=T)) %>% 
  ungroup() 

head(coral_health_monthly)

write_csv(coral_health_monthly,"data_tidy/coral_health_monthly.csv")  #output clean csv
```


#Try some test visualizations

```{r }
head(coral_health_monthly,20)
plot(health_score_mean ~ year_month, coral_health_monthly) #base plot

recovery_plot<- ggplot(coral_health_monthly, aes(x=year_month, y=health_score_mean, color=species)) + 
  geom_point()
recovery_plot + facet_wrap(~reef)+ theme_bw()

```

Now facet across species, plotting reefs in diff. color
```{r}
recovery_plot2<- ggplot(coral_health_monthly, aes(x=year_month, y=health_score_mean, color=reef)) + 
  geom_point()
recovery_plot2 + facet_wrap(~species)+ theme_bw()
```

