---
title: "zoox_conc"
author: "GG"
date: "March 14, 2018"
output: html_document
---

## Libraries

```{r setup, message=FALSE, warning=FALSE}
library(tidyverse)
library(dplyr)
library(lubridate)
```

## Import the csv file
```{r, results='hide'}

zoox <- read.csv("https://raw.githubusercontent.com/robertpdunn/kbay_physical/master/data_raw/bleaching_symbionts.csv")
head(zoox)

```


##Now remove unused columns

```{r}
head(zoox)

zoox_min <- select(zoox, colony, date, reef, C.SH, D.SH, tot.SH, vis, days)
head(zoox_min)
```
##check that vis doesn't vary within colonies  (apologies for this )
```{r}
any(
  sapply(
    split(zoox$vis,paste(zoox$reef,zoox$colony)),
        function(x) length(unique(x[!is.na(x)]))
        )
  >1)
```



##Ok, now I want to create a new column that will transform date from a character to date using as.Date and mutate. 

```{r}
zoox_monthly <- zoox_min %>% 
  mutate(date_formatted = as.Date(date, "%m/%d/%y")) %>% 
  mutate(year_month = floor_date(date_formatted, "month")) %>%
  mutate(bleached=ifelse(vis=="bleached",TRUE,FALSE)) %>% 
  select(colony, year_month, reef, bleached, clade_c=C.SH, clade_d=D.SH, total_zoox=tot.SH, days, date_formatted, date)


```

## Average zoox data by month - also split out vis
*also needed to reformat zoox concentration to numeric*
```{r}
zoox_mean_monthly <- zoox_monthly %>% 
  group_by(reef, year_month,bleached) %>%
  summarise(clade_c_mean=mean(as.numeric(clade_c)), clade_d_mean=mean(as.numeric(clade_d)),total_zoox_mean=mean(as.numeric(total_zoox))) %>% 
  ungroup() 
```

```{r}
write.csv(zoox_mean_monthly, file = "data_tidy/zoox_mean_monthly.csv", row.names = FALSE)
```

First attempt at a plot

```{r}
zoox_mean_monthly <- read_csv("data_tidy/zoox_mean_monthly.csv")

ggplot(data = zoox_mean_monthly, aes(x=year_month, y = total_zoox_mean, color = bleached, shape = reef)) + geom_point(size = 3)
```


























