---
title: "Temperature data import and tidy"
author: "Ross Cunning"
date: "3/14/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tibbletime)
library(lubridate)
```

```{r read_temp_data}
reef25_2014 <- read_csv("https://zenodo.org/record/46366/files/temp_reef25_2014.csv") %>%
  mutate(temp = temp_raw_C,
         date = as.Date(date, format="%m/%d/%Y")) %>%  # Reformat date and convert to date class 
  select(date, time, temp)

reef25_2015 <- read_csv("https://zenodo.org/record/46366/files/temp_reef25_2015.csv") %>%
  mutate(temp = temp_raw_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reef25_2016 <- read_csv("data_raw/temp_rf25_2016.csv") %>%
  mutate(temp = temp_cal_C) %>% 
  select(date, time, temp)

reef42_2014 <- read_csv("https://zenodo.org/record/46366/files/temp_reef42_2014.csv") %>%
  mutate(temp = temp_raw_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reef42_2015 <- read_csv("https://zenodo.org/record/46366/files/temp_reef42_2015.csv") %>%
  mutate(temp = temp_raw_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reef42_2016 <- read_csv("data_raw/temp_rf42_2016.csv") %>%
  mutate(temp = temp_raw_C) %>% 
  select(date, time, temp)

reef44_2014 <- read_csv("https://zenodo.org/record/46366/files/temp_reef44_2014.csv") %>%
  mutate(temp = temp_cal_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reef44_2015 <- read_csv("https://zenodo.org/record/46366/files/temp_reef44_2015.csv") %>%
  mutate(temp = temp_cal_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reef44_2016 <- read_csv("data_raw/temp_rf44_2016.csv") %>%
  mutate(temp = temp_cal_C) %>% 
  select(date, time, temp)

reefHIMB_2014 <- read_csv("https://zenodo.org/record/46366/files/temp_reefHIMB_2014.csv") %>%
  mutate(temp = temp_cal_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reefHIMB_2015 <- read_csv("https://zenodo.org/record/46366/files/temp_reefHIMB_2015.csv") %>%
  mutate(temp = temp_cal_C,
         date = as.Date(date, format="%m/%d/%Y")) %>% 
  select(date, time, temp)

reefHIMB_2016 <- read_csv("data_raw/temp_rfHIMB_2016.csv") %>%
  mutate(temp = temp_cal_C) %>% 
  select(date, time, temp)
```

```{r combine_temp_data}
reef25 <- bind_rows(reef25_2014, reef25_2015, reef25_2016) %>% mutate(reef = "reef_25")
reef44 <- bind_rows(reef44_2014, reef44_2015, reef44_2016) %>% mutate(reef = "reef_44")
reef42 <- bind_rows(reef42_2014, reef42_2015, reef42_2016) %>% mutate(reef = "reef_42")
reefHIMB <- bind_rows(reefHIMB_2014, reefHIMB_2015, reefHIMB_2016) %>% mutate(reef = "reef_himb")

temp_data <- bind_rows(reef25, reef44, reef42, reefHIMB)
temp_data$date <- as.Date(temp_data$date, format="%m/%d/%Y")  # Reformat date and convert to date class
temp_data
```

```{r daily_temp_metrics}
temp_daily <- temp_data %>%
  group_by(reef, date) %>%
  summarise(temp_mean = mean(temp),
            temp_max = max(temp),
            temp_min = min(temp),
            temp_var = var(temp))

temp_daily

temp_monthly <- temp_daily %>%
  group_by(reef, month = month(date), year = year(date)) %>%
  summarise(temp_mean_daily_mean = mean(temp_mean),
            temp_mean_daily_max = mean(temp_mean),
            temp_mean_daily_min = mean(temp_min),
            temp_mean_daily_var = mean(temp_var)) %>%
  ungroup() %>%
  mutate(date = as.Date(paste(year, month, "01", sep="-"), format="%Y-%m-%d")) %>%
  select(date, reef, temp_mean_daily_mean, temp_mean_daily_min, temp_mean_daily_max, temp_mean_daily_var)

temp_monthly

# Write tidy temperature data to file
write_csv(temp_monthly, path = "data_tidy/temp_monthly.csv")
```

